### ISSUE TITLE
3 Errors not working

### ISSUE THREAD

**Issue by Ra1n6666** [MasterLua/EzExecV2#5]
![image](https://user-images.githubusercontent.com/99132840/154545020-13ab8f34-4c22-4e24-a233-9d14d407e4ce.png)
![image](https://user-images.githubusercontent.com/99132840/154545046-3651efb3-a585-4a50-881c-4723f43c0bef.png)

**Comment by HjInYoMaMa** [comment]
idiot

**Comment by MadrisAkb** [comment]
> ![image](https://user-images.githubusercontent.com/99132840/154545020-13ab8f34-4c22-4e24-a233-9d14d407e4ce.png) ![image](https://user-images.githubusercontent.com/99132840/154545046-3651efb3-a585-4a50-881c-4723f43c0bef.png)

Change thé settings in visual studio
